server:
  port: 8077

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:C:/Users/Gilink15/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  Security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lij5STuc8y9nNySl
            client-secret: ec72a738bfc1bc14bdc3049d0ac09a1adb6e649d
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
jwt:
  secret: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
  expiration: 3600000